import mongoose from 'mongoose';
const userSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    isVerified:{
        type:Boolean,
        default:false
    },
    allowPasswordChange:{
        type:Boolean,
        default:false
    },
    password:{
        type:String,
        required:true
    }
})
const userModel=mongoose.model('user',userSchema);
const emailSchema=new mongoose.Schema({
    to:{
        type:String,
        required:true
    },
    from:{
        type:String,
        required:true
    },
    subject:String,
    body:String,
    time:{
        type:String,
        required:true
    },
    date:{
        type:String,
        required:true
    },
    image:String,
    name:{
        type:String,
        required:true
    },
    starred:{
        type:Boolean,
        required:true,
        default:false
    },
    bin:{
        type:Boolean,
        required:true,
        default:false
    },
    general:{
        type:Boolean,
        required:false,
        default:true
    },
    readed:{
        type:Boolean,
        required:false,
        default:false
    },
    important:{
        type:Boolean,
        required:false,
        default:false
    },
    spam:{
        type:Boolean,
        required:false,
        default:false
    },
    archived:{
        type:Boolean,
        required:false,
        default:false
    }
})
const emailModel=mongoose.model('emails',emailSchema);
export {userModel,emailModel};